#!/usr/bin/env sh
# This line specifies the shell to use for executing the script
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged
# This line runs lint-staged, which will lint only the files that are staged for commitnpx lint-staged
